### ISSUE TITLE
Incorrect data for card id=xy5-149 and xy5-55's evolvesFrom

### ISSUE THREAD

**Issue by brianchan661** [PokemonTCG/pokemon-tcg-data#110]
Both card is "Primal Kyogre-EX" and its"evolvesFrom" is set as "Primal Kyogre-EX".
I think its should be "Kyogre-EX" instead.

same case for xy5-86 and ex5-151 Primal Groudon-EX

ref: https://api.pokemontcg.io/v1/cards?name="Primal Kyogre-EX"

**Comment by adback03** [comment]
This has been fixed.
