### ISSUE TITLE
Ultra Prism does not exist yet

### ISSUE THREAD

**Issue by developingchris** [PokemonTCG/pokemon-tcg-data#12]
This isn't an issue to stir anything up , but merely to start the conversation around helping maintain the data.

I would like to start using this data in an application, and want to make sure I can help maintain the data set.

Are you generating the data off of another site? Or is it all manual data entry?

**Comment by adback03** [comment]
Most of the data is automatically gathered. Bits of it need to get pieced together manually in case some cards (like secret rares) aren't available.

This is actually a good time to talk about how the cards with a Prism in their name should be represented in the API.

Example: https://www.pokemon.com/us/pokemon-tcg/pokemon-cards/sm-series/sm5/62/

Should the card name be "Lunala ◇" or something like "Lunala Prism"?

**Comment by developingchris** [comment]
they seem to refer to that symbol as "Prism Star" which is  bit awkward.   So it's being called "Lunala Prism Star" or  "Prism Star Solgaleo" when I heard them talked about at the pre-release

**Comment by developingchris** [comment]
I'd like to contribute to the automated way to gather this data.
I started building out a scraper, but I assume you already have something close to what I am headed for.

**Comment by r0adkll** [comment]
It appears that Pokemon has posted the official card data to their site now.

**Comment by developingchris** [comment]
@r0adkll  what are you guys using to scrape and populate the data?

**Comment by r0adkll** [comment]
You'll have to ask @adback03 as he built/runs the scraper. I just submit corrections and missing cards via this repo

**Comment by spicasax** [comment]
> Should the card name be "Lunala ◇" or something like "Lunala Prism"?

If we kept it as "Lunala ◇", it would be consistent with other sets.

Example:
"Beedrill δ" instead of "Beedrill Delta" as found here:

https://github.com/PokemonTCG/pokemon-tcg-data/blob/master/json/cards/Delta%20Species.json#L4

However, for readability sake, "Lunala ◇" is confusing. So, to be consistent or readable? Hmmm.

**Comment by r0adkll** [comment]
@spicasax I would say the symbol is fine as long as the server knows to search for it when the user enters "Prism" or "Prism Star" (this is how Proxycroak works). As far as displaying it, in my app regardless of symbol or word, I plan to regex it out and insert the actual icon as a span.

So I would probably be in favor of using the symbol to keep consistent

**Comment by spicasax** [comment]
Yeah, I'm also cool with keeping it symbols for consistency sake. It doesn't matter for my usage.

**Comment by adback03** [comment]
Hey all. The initial load of Ultra Prism is now available. Rarities and Hi-res images still need to get added. I might be able to get to rarity tonight, but feel free to make a PR for that. I'll make issues for both for tracking purposes.
