### ISSUE TITLE
No category for Held Items

### ISSUE THREAD

**Issue by MatiasOETamminen** [PokemonTCG/pokemon-tcg-data#123]
The Held Items that were in the game during the DPP era don't have their own category but are "bare" in the data. Would it be possible to have a category for them?

For example, compare the following cards:
`{
    "id": "dp2-2",
    "name": "Alakazam",
    "imageUrl": "https://images.pokemontcg.io/dp2/2.png",
    "subtype": "Stage 2",
    "supertype": "Pokémon",
    "level": "47",
    "evolvesFrom": "Kadabra",
    "ability": {
      "name": "Power Cancel",
      "text": "Once during your opponent's turn, when your opponent's Pokémon uses any Poké-Power, you may discard 2 cards from your hand and prevent all effects of that Poké-Power. (This counts as that Pokémon using its Poké-Power.) This power can't be used if Alakazam is affected by a Special Condition.",
      "type": "Poké-Power"
    },
    "hp": "100",
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "2",
    "artist": "Kouki Saitou",
    "rarity": "Rare Holo",
    "series": "Diamond & Pearl",
    "set": "Mysterious Treasures",
    "setCode": "dp2",
    "types": [
      "Psychic"
    ],
    "attacks": [
      {
        "name": "Psychic Guard",
        "cost": [
          "Psychic",
          "Psychic",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "50",
        "text": "During your opponent's next turn, any damage done to Alakazam by attacks from your opponent's Stage 2 Evolved Pokémon is reduced by 30 (after applying Weakness and Resistance)."
      }
    ],
    "weaknesses": [
      {
        "type": "Psychic",
        "value": "+30"
      }
    ],
    "imageUrlHiRes": "https://images.pokemontcg.io/dp2/2_hires.png",
    "nationalPokedexNumber": 65
  },`

` {
    "id": "dp2-73",
    "name": "Bidoof",
    "imageUrl": "https://images.pokemontcg.io/dp2/73.png",
    "subtype": "Basic",
    "supertype": "Pokémon",
    "level": "11",
    "hp": "60",
    "retreatCost": [
      "Colorless",
      "Colorless"
    ],
    "convertedRetreatCost": 2,
    "number": "73",
    "artist": "Yusuke Ohmura",
    "rarity": "Common",
    "series": "Diamond & Pearl",
    "set": "Mysterious Treasures",
    "setCode": "dp2",
    "text": [
      "Any damage done to Bidoof by attacks from Lightning Pokémon is reduced by 20 (after applying Weakness and Resistance)."
    ],
    "types": [
      "Colorless"
    ],
    "attacks": [
      {
        "name": "Tackle",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "30",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "+10"
      }
    ],
    "imageUrlHiRes": "https://images.pokemontcg.io/dp2/73_hires.png",
    "nationalPokedexNumber": 399,
    "evolvesTo": [
      "Bibarel"
    ]
  },`

**Comment by adback03** [comment]
These items are included as part of the "rules" array in V2 of the API. As of now, there are no plans to give this its own field.
