### ISSUE TITLE
Gym Challenge - Logo image quality

### ISSUE THREAD

**Issue by haroutig** [PokemonTCG/pokemon-tcg-data#124]
The gym challenge logo image at 

https://images.pokemontcg.io/gym2/logo.png

does not have a stroke around it's borders like gym heroes does, resulting in a very poor look on darker backdrops. Example:

<img width="353" alt="Screen Shot 2020-02-21 at 5 34 50 PM" src="https://user-images.githubusercontent.com/42183391/75078173-eb8d6900-54d2-11ea-8f0a-c1fb4a25c7e8.png">

I have fixed the issue in Photoshop and attached a possible replacement PNG that could be used.

![logo](https://user-images.githubusercontent.com/42183391/75078510-c3ead080-54d3-11ea-9f2b-f91bd9179245.png)

**Comment by adback03** [comment]
Sorry for taking so long to address this. Thanks for the updated logo! I have uploaded it.
