### ISSUE TITLE
Aquapolis and Skyridge IDs on cards numbered H1–H32

### ISSUE THREAD

**Issue by MatiasOETamminen** [PokemonTCG/pokemon-tcg-data#126]
The cards numbered H1–H32 in both Aquapolis and Skyridge have their ids weirdly appended to the end of the set. For example, ecard2-H1 is ecard2-151 (the set has 150 "regular" cards). Could this be changed to the actual number? Of course, the scan URLs contain the "appended" ID.

**Comment by adback03** [comment]
This is a side effect from a previous issue where the cards were originally numbered incorrectly. Unfortunately, I cannot update the IDs in version 1 of this API, as that would have breaking changes for people integrating with it.

I'll leave the issue with a v2 tag on it.

**Comment by adback03** [comment]
This has been fixed with the launch of V2.
