### ISSUE TITLE
Rarity

### ISSUE THREAD

**Issue by ProfessorOaksLab** [PokemonTCG/pokemon-tcg-data#132]
We had some discussion here https://github.com/PokemonTCG/pokemon-tcg-data/issues/127 and here https://github.com/PokemonTCG/pokemon-tcg-data/issues/128 which involved rarities.

So I created a small script to cross-check the rarities in the API toward scraped rarities from different sources. Below are the ones that did not match what we have and might be something we want to look over.

Number: 113
Expansion: FireRed & LeafGreen
API: Rare Holo
Scraped: Ultra Secret

Number: 110
Expansion: Team Rocket Returns
API: Rare Holo
Scraped: Rare Secret

Number: 111
Expansion: Team Rocket Returns
API: Rare Holo
Scraped: Rare Secret

Number: 107
Expansion: Emerald
API: Rare Holo
Scraped: Rare Secret

Number: 113
Expansion: Unseen Forces
API: Rare Holo
Scraped: Ultra Rare

Number: 114
Expansion: Unseen Forces
API: Rare Holo
Scraped: Ultra Rare

Number: 115
Expansion: Unseen Forces
API: Rare Holo
Scraped: Ultra Rare

Number: 111
Expansion: Delta Species
API: Rare Holo
Scraped: Ultra rare

Number: 112
Expansion: Delta Species
API: Rare Holo
Scraped: Ultra rare

Number: 113
Expansion: Delta Species
API: Rare Holo
Scraped: Ultra rare

Number: 17
Expansion: POP Series 2
API: Rare Holo
Scraped: Rare Holo Ex

Number: 17
Expansion: POP Series 3
API: Rare Holo
Scraped: Rare Holo Ex

Number: 17
Expansion: POP Series 4
API: Rare Holo
Scraped: Rare Holo Ex

Number: 16
Expansion: POP Series 5
API: Rare Holo
Scraped: Rare Holo Ex

Number: 17
Expansion: POP Series 5
API: Rare Holo
Scraped: Rare Holo Ex

Number: 124
Expansion: Mysterious Treasures
API: Rare Holo
Scraped: Secret Rare

Number: 58
Expansion: Great Encounters
API: Common
Scraped: Uncommon

Number: 59
Expansion: Great Encounters
API: Common
Scraped: Uncommon

Number: SL01
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL02
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL03
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL04
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL05
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL06
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL07
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL08
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL09
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL10
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: SL11
Expansion: Call of Legends
API: Rare Holo
Scraped: Ultra Rare

Number: 102
Expansion: Noble Victories
API: Rare Holo
Scraped: Rare Secret

Number: 100
Expansion: Next Destinies
API: Rare Holo
Scraped: Rare Secret

Number: 109
Expansion: Dark Explorers
API: Rare Holo
Scraped: Rare Secret

Number: 110
Expansion: Dark Explorers
API: Rare Holo
Scraped: Rare Secret

Number: 111
Expansion: Dark Explorers
API: Rare Holo
Scraped: Rare Secret

Number: 119
Expansion: Dragons Exalted
API: Rare Ultra
Scraped: Rare Holo EX

Number: 120
Expansion: Dragons Exalted
API: Rare Ultra
Scraped: Rare Holo EX

Number: 121
Expansion: Dragons Exalted
API: Rare Ultra
Scraped: Rare Holo EX

Number: 122
Expansion: Dragons Exalted
API: Rare Ultra
Scraped: Rare Holo EX

Number: 123
Expansion: Dragons Exalted
API: Rare Ultra
Scraped: Rare Holo EX

Number: 124
Expansion: Dragons Exalted
API: Rare Ultra
Scraped: Rare Holo EX

Number: 125
Expansion: Dragons Exalted
API: Rare Holo
Scraped: Rare Secret

Number: 126
Expansion: Dragons Exalted
API: Rare Holo
Scraped: Rare Secret

Number: 127
Expansion: Dragons Exalted
API: Rare Holo
Scraped: Rare Secret

Number: 128
Expansion: Dragons Exalted
API: Rare Holo
Scraped: Rare Secret

Number: 86
Expansion: Boundaries Crossed
API: Uncommon
Scraped: Common

Number: 87
Expansion: Boundaries Crossed
API: Common
Scraped: Uncommon

Number: 132
Expansion: Boundaries Crossed
API: Uncommon
Scraped: Common

Number: 141
Expansion: Boundaries Crossed
API: Rare Ultra
Scraped: Rare Holo EX

Number: 142
Expansion: Boundaries Crossed
API: Rare Ultra
Scraped: Rare Holo EX

Number: 143
Expansion: Boundaries Crossed
API: Rare Ultra
Scraped: Rare Holo EX

Number: 144
Expansion: Boundaries Crossed
API: Rare Ultra
Scraped: Rare Holo EX

Number: 145
Expansion: Boundaries Crossed
API: Rare Ultra
Scraped: Rare Holo EX

Number: 146
Expansion: Boundaries Crossed
API: Rare Ultra
Scraped: Rare Holo EX

Number: 150
Expansion: Boundaries Crossed
API: Rare Holo
Scraped: Rare Secret

Number: 151
Expansion: Boundaries Crossed
API: Rare Holo
Scraped: Rare Secret

Number: 152
Expansion: Boundaries Crossed
API: Rare Holo
Scraped: Rare Secret

Number: 153
Expansion: Boundaries Crossed
API: Rare Holo
Scraped: Rare Secret

Number: 131
Expansion: Plasma Storm
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 132
Expansion: Plasma Storm
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 133
Expansion: Plasma Storm
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 134
Expansion: Plasma Storm
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 136
Expansion: Plasma Storm
API: Rare Holo
Scraped: Rare Secret

Number: 137
Expansion: Plasma Storm
API: Rare Holo
Scraped: Rare Secret

Number: 138
Expansion: Plasma Storm
API: Rare Holo
Scraped: Rare Secret

Number: 109
Expansion: Plasma Freeze
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 110
Expansion: Plasma Freeze
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 111
Expansion: Plasma Freeze
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 112
Expansion: Plasma Freeze
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 113
Expansion: Plasma Freeze
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 114
Expansion: Plasma Freeze
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 117
Expansion: Plasma Freeze
API: Rare Holo
Scraped: Rare Secret

Number: 118
Expansion: Plasma Freeze
API: Rare Holo
Scraped: Rare Secret

Number: 119
Expansion: Plasma Freeze
API: Rare Holo
Scraped: Rare Secret

Number: 120
Expansion: Plasma Freeze
API: Rare Holo
Scraped: Rare Secret

Number: 121
Expansion: Plasma Freeze
API: Rare Holo
Scraped: Rare Secret

Number: 122
Expansion: Plasma Freeze
API: Rare Holo
Scraped: Rare Secret

Number: 96
Expansion: Plasma Blast
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 97
Expansion: Plasma Blast
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 98
Expansion: Plasma Blast
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 99
Expansion: Plasma Blast
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 100
Expansion: Plasma Blast
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 101
Expansion: Plasma Blast
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 102
Expansion: Plasma Blast
API: Rare Holo
Scraped: Rare Secret

Number: 103
Expansion: Plasma Blast
API: Rare Holo
Scraped: Rare Secret

Number: 104
Expansion: Plasma Blast
API: Rare Holo
Scraped: Rare Secret

Number: 105
Expansion: Plasma Blast
API: Rare Holo
Scraped: Rare Secret

Number: 114
Expansion: Legendary Treasures
API: Rare Holo
Scraped: Rare Secret

Number: 115
Expansion: Legendary Treasures
API: Rare Holo
Scraped: Rare Secret

Number: RC21
Expansion: Legendary Treasures
API: Rare Ultra
Scraped: Rare Holo Ex

Number: RC24
Expansion: Legendary Treasures
API: Rare Ultra
Scraped: Rare Holo Ex

Number: RC25
Expansion: Legendary Treasures
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 141
Expansion: XY
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 142
Expansion: XY
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 143
Expansion: XY
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 144
Expansion: XY
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 145
Expansion: XY
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 146
Expansion: XY
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 100
Expansion: Flashfire
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 101
Expansion: Flashfire
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 102
Expansion: Flashfire
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 103
Expansion: Flashfire
API: Rare Ultra
Scraped: Rare Holo Ex

Number: 107
Expansion: Flashfire
API: Rare Holo
Scraped: Rare Secret

Number: 108
Expansion: Flashfire
API: Rare Holo
Scraped: Rare Secret

Number: 109
Expansion: Flashfire
API: Rare Holo
Scraped: Rare Secret

**Comment by adback03** [comment]
All sets have been rebuilt with v2 and rarities updated. If you still see issues, please open a new issue. Thank you!
