### ISSUE TITLE
SWSH Black Star promos missing

### ISSUE THREAD

**Issue by MatiasOETamminen** [PokemonTCG/pokemon-tcg-data#137]
One list of 'em here: https://bulbapedia.bulbagarden.net/wiki/SWSH_Black_Star_Promos_(TCG)

**Comment by blacktide082** [comment]
Here's another list with hi-res images (all English) as well.
https://pkmncards.com/set/sword-shield-promos/

**Comment by luzer** [comment]
i am having the same issue with https://pkmncards.com/card/armored-mewtwo-sun-moon-promos-sm228/

**Comment by adback03** [comment]
Thanks, Sword and Shield promos are now available. Sorry for the delay!
