### ISSUE TITLE
Missing image for SM93 Black Star Promo

### ISSUE THREAD

**Issue by blacktide082** [PokemonTCG/pokemon-tcg-data#139]
The card here appears to be missing an image:
https://pokemontcg.io/cards/smp-sm93

I've attached the correct image (I wasn't able to find a hi-res `.png`) file.

![sm93_hires](https://user-images.githubusercontent.com/61211787/86489799-73ae3580-bd33-11ea-8415-ac5e8a309e84.jpg)

**Comment by adback03** [comment]
Thank you, this has been fixed.
