### ISSUE TITLE
JSON newline sequence "\\n\\n" escapes to "\n\n" on client

### ISSUE THREAD

**Issue by acupoftee** [PokemonTCG/pokemon-tcg-data#147]
The current scape sequence renders card descriptions with the escape sequence still present. Resolving this would be a good quality of life fix for developers. Below is an example of this with Recycle Energy ([`sm11-257`](https://pokemontcg.io/cards/sm11-257)):

### Current JSON (`card.text`)
```json
    "text": [
      "This card provides Colorless Energy.\\n\\nIf this card is discarded from play, put it into your hand instead of the discard pile."
    ]
```

### Client Results
<img width="617" alt="Screen Shot 2020-08-15 at 5 22 52 PM" src="https://user-images.githubusercontent.com/15068267/90322491-e01b7780-df22-11ea-9a43-54dab8a0ea49.png">

See https://github.com/PokemonTCG/pokemon-tcg-data/pull/146 for the fix

**Comment by adback03** [comment]
Thanks for the PR, this has been merged.
