### ISSUE TITLE
Shiny Vault set logoUrl is returning Hidden Fates logo

### ISSUE THREAD

**Issue by cssagogo** [PokemonTCG/pokemon-tcg-data#151]
Getting the wrong logoUrl back for Shiny Vault.

**Comment by flagrama** [comment]
Does shiny vault have a logo? It's just a subset of Hidden Dates. I would expect it to have the hidden fates logo.

**Comment by adback03** [comment]
From my understanding, @flagrama is correct. If someone wants to point to a different logo, let me know, but it seems like it is the same logo.
