### ISSUE TITLE
FEATURE: Add a /pokemon endpoint

### ISSUE THREAD

**Issue by cssagogo** [PokemonTCG/pokemon-tcg-data#153]
It would be super helpful to have a pokemon endpoint that accepts a name param and returns a unique set of card names based on it.

https://api.pokemontcg.io/v1/pokemon?name=pika

Would result in something like this...

```
"pokemon": [{
  "name": "Pikachu-EX",
  "firstAppeared: "Date",
  "firstSet": "setid" ,
  ... 
},{
  "name": "Pikachu",
  "firstAppeared: "Date",
  "firstSet": "setid",
  ... 
},{
  "name": "Pikachu & Zekrom-GX",
  "firstAppeared: "Date",
  "firstSet": "setid" ,
  ...  
}]
```

Haven't thought through all the fields that would make sense here, but even having a unique list of names available would be great!

**Comment by daoneandonly** [comment]
Would this be any different than `https://api.pokemontcg.io/v1/cards?name=pika` ?

**Comment by adback03** [comment]
Right now this can be accomplished using nationalPokedexNumbers and sorting on the set.releaseDate to see the earliest date and set that it appeared in.

For example:

```
https://api.pokemontcg.io/v2/cards?q=nationalPokedexNumbers:3&orderBy=set.releaseDate
```

That will return all cards with Venusaur, ordered by release date.
