### ISSUE TITLE
CPA is missing 7 cards (73 out of 80)

### ISSUE THREAD

**Issue by lfgcampos** [PokemonTCG/pokemon-tcg-data#154]
[Champion's Path](https://pokemontcg.io/cards?setCode=swsh35) has only 73 cards while it should have 80.

**Comment by lfgcampos** [comment]
Hey @adback03, quick question here.
How do you update the repo? Do you have a scrapper because I don't believe you do it by hand =)

I know places where we could get all the missing info for cards and most of the collections but updating all of them by hand wouldn't be a nice job.

**Comment by xqus** [comment]
I bet it is updated from the JSON files. So if you want to add missing information you can edit the files here.

**Comment by lfgcampos** [comment]
@xqus yes, that part I know. I just don't think he adds/edits the jsons by hand every time there is a new collection or a fix to be made. I believe it is somewhat automated.

**Comment by xqus** [comment]
@lfgcampos Yeah, sorry for stating the obvious. I'm working on a tool that will generate the JSON from a form, but I think the JSON he generates are created from the database, but it would be interesting to know how he updates it as updating the JSON directly are extremely cumbersome.

**Comment by lfgcampos** [comment]
No worries @xqus , I am just asking because the community has already put something together for that.
For example, [this repo](https://github.com/kirbyUK/ptcgo-data) is 'always' updated with the latest info from ptcgo and follow the same json structure from here (eg: it already have all 80 cards from CPA). We could easily (try to) integrate both repos, I just wanted to know how he does it to try to help.

**Comment by xqus** [comment]
@lfgcampos I didn't know about that repository. There should really be a way to pull data from that into this repo. I see it is missing some fields, like artist, set and image.

**Comment by adback03** [comment]
This has been fixed with #157. As far as where the data comes from, it is a mix of sources, but primarily pokemon.com. Kirby's repo you pointed to pulls data from the PTCGO client, which unfortunately doesn't expose fields like artist. But yes, setting something up to work between the two wouldn't be too difficult. I wouldn't put a ton of effort into it right now though, as V2 of this API is currently in beta, and the schema as some changes.

**Comment by lfgcampos** [comment]
@adback03 thanks for the update regarding v2. Where can we see the status of it? And probably contribute =)

**Comment by adback03** [comment]
@lfgcampos I'm in the process of updating the main site with details on V2. For now, you can check out the discord. I'll be posting updates there and answering questions about it as well. Here is the original announcement: https://discordapp.com/channels/222559292497068043/222559292497068043/763764992989593640

Once the schema is finalized (close to this), I will update the main website with details on how to use it, and put out an official deprecation warning of v1, with support ending at some point in 2021 (I'll give at least 6 months for people to update).
