### ISSUE TITLE
submission request: new images for EX3 (EX Dragon)

### ISSUE THREAD

**Issue by jparanada** [PokemonTCG/pokemon-tcg-data#165]
I've been slowly upgrading old card images to use hi-res scans, and I'd really love to submit those images here! A complete set of pngs for EX Dragon is here--all 100 cards at 734x1024 resolution, plus the 3 secret-rare cards in small resolution (245x342) as well:

https://cdn.malie.io/file/malie-io/art/scans/submissions/ex3_dr_pngs.zip

If you just want a quick preview of what the new images look like, they are here: https://pkmncards.com/set/dragon/ (but don't actually use the ones on pkmncards, since they're lossy jpg... use the ones in the zip instead).

**Comment by adback03** [comment]
Thank you for this! I have updated the images. It might take a few hours for the cache to show the new ones.
