### ISSUE TITLE
Extra "s" in URL protocols in "link" Response Header 

### ISSUE THREAD

**Issue by veekose** [PokemonTCG/pokemon-tcg-data#168]
The "link" value in the response headers has an extra "s" in the URL protocols.

**Steps to reproduce:**
1. Make any data call to the Pokemon TCG API
2. Check the "link" value in the response headers

**Expected:** The protocols mentioned in the URLs should be "https"

**Actual:** The protocols mentioned in the URLs are "httpss"

![image](https://user-images.githubusercontent.com/31103375/103967863-7a759500-5128-11eb-93f1-3e451faeb3c8.png)

**Comment by adback03** [comment]
Thanks for reporting this. Unfortunately V1 of the API is deprecated, and I will not be making any additional updates to it. It is highly recommended you update to V2, as V1 will be unavailable as of August 1st, 2021.
