### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by remy-poirier** [PokemonTCG/pokemon-tcg-data#171]
Hello,

I am using your API in order to create a website that allows user to manager their card collections.

I just want to know some things:

- Is there a possibility to specify a locale when calling endpoints ? I am interested in French only
- Also, can I know if a card is available in Reverse or no ?
- Finally, can I get the icon next to the card number ? It can be useful in my case to identify cards set.

**Comment by mbret** [comment]
As far as I know and by looking at the raw data there is no local, only a couple of french card i found somewhere but not sure how to retrieve them.

I made an app that we use for japanese cards and I had to build a script that scrap bulbapedia to enrich the db with japanese set numbers. You can probably use my script as a base to loop through bulbapedia from this db and enrich your data with what you want. Feel free if it helps you.

`https://github.com/mbret/pokemax/blob/master/scripts/fetch_and_update_db.ts` create or update the db with latest data from here
`https://github.com/mbret/pokemax/blob/master/scripts/enrich_db.ts` enrich the db with japanese value

Code is dirty, this is a week end project ^^

**Comment by adback03** [comment]
Foreign language support is a feature that will be coming in the future. It is one of the first enhancements to V2 of the API that I will be working on.

As far as getting the icon goes, you can get the icon for a given set via the `sets` endpoint.
