### ISSUE TITLE
Promo Legality an Issue in V2

### ISSUE THREAD

**Issue by Dillonzer** [PokemonTCG/pokemon-tcg-data#172]
Currently all of Sun and Moon Black Star Promos are showing legal when in reality Black Star Promo cards numbered SM158 and up and SWSH001 and up are standard Legal.

Also an issue with Alternate Arts listing as Legal when they actually aren't (SV002 for example).

Also Reprints from older sets are not showing as legal either (ie; Pokedex from Base Set is legal in Expanded due to EVO set)

The way I tackled this was having a class specifically for Bans / Reprints to overwrite legality on cards so you don't have to manually edit the data. Let me know if you need help regarding this.

**Comment by adback03** [comment]
So how do you know if a given card is a reprint? Is matching on the card name enough?

**Comment by adback03** [comment]
I believe I have fixed the promo legalities and other sets being an issue, just still need to figure out a good way for reprints.

**Comment by Dillonzer** [comment]
@adback03 sorry, was working. Reprints have to have the same Card Text, Card Name, Abilities, Costs, everything. Luckily I believe @immewnity did some hard work on some Reprint information here:
Expanded: https://pokegym.net/current-expanded-legal-card-list/
Standard: https://pokegym.net/current-standard-legal-card-list/

Best way imo would be to have something check the return payload and run through a legality converter and change them based on the convertor. They way you only need to update the convertor to deal with Bans / Reprints / Promos. You can still copy the base legality from Sets this way.

**Comment by immewnity** [comment]
I can't take the credit for that - PokePop does all the maintenance work on it. All I've done is tried to make it look pretty :)

Cards can have different text as long as the function is identical, but that's usually something that needs confirmation from TPCi (which the above lists take into account).

**Comment by MatiasOETamminen** [comment]
To piggyback on this issue, also the Shining Fates cards have legality status missing.

**Comment by MatiasOETamminen** [comment]
This has been fixed and can be closed
