### ISSUE TITLE
The PTCGO code field for the Sword & Shield promos set is incorrect

### ISSUE THREAD

**Issue by Jake-Gearhart** [PokemonTCG/pokemon-tcg-data#174]
When you export Sword & Shield promos from PTCGO, take Snorlax (SWSH068) for example, the export looks like: 
`* 1 Snorlax PR-SW 68`
However in the API, the Sword & Shield promo set's PTCGO code is PR-SWSH. I don't believe this issue affects any other promo sets.

**Comment by adback03** [comment]
Thanks, this has been updated.
