### ISSUE TITLE
Shining Fates is not marked as a legal set

### ISSUE THREAD

**Issue by stebaker92** [PokemonTCG/pokemon-tcg-data#175]
From the `/sets/` endpoint, Shining Fates comes back with the `standardLegal` and `expandedLegal` properties set to false, despite the official Pokemon website stating this set is 'Standard Legal Deck'

Source:
https://www.pokemon.com/uk/pokemon-tcg/shining-fates/explore-and-watch/

**Comment by adback03** [comment]
Thank you, the legality info has now been updated.
