### ISSUE TITLE
Rarity wrong on gym2-127

### ISSUE THREAD

**Issue by Maximo1491** [PokemonTCG/pokemon-tcg-data#177]
Hi,

Looks like the rarity on https://pokemontcg.guru/card/fighting-energy-gym/gym2-127 has N/A set for its rarity when I'm assuming it should be Common

**Comment by SiWoC** [comment]
My check reveals 77 cards without rarity

gym2-127 Energy Fighting Energy
si1-1 Pokémon Mew
si1-2 Pokémon Pidgeot
si1-3 Pokémon Onix
si1-4 Pokémon Togepi
si1-5 Pokémon Ivysaur
si1-6 Pokémon Raticate
si1-7 Pokémon Ledyba
si1-8 Pokémon Jigglypuff
si1-9 Pokémon Butterfree
si1-10 Pokémon Tentacruel
si1-11 Pokémon Marill
si1-12 Pokémon Lapras
si1-13 Pokémon Exeggutor
si1-14 Pokémon Slowking
si1-15 Pokémon Wartortle
si1-16 Pokémon Lickitung
si1-17 Pokémon Vileplume
si1-18 Pokémon Primeape
ru1-1 Pokémon Venusaur
ru1-2 Pokémon Cherrim
ru1-3 Pokémon Ninetales
ru1-4 Pokémon Heatran
ru1-5 Pokémon Starmie
ru1-6 Pokémon Gyarados
ru1-7 Pokémon Pikachu
ru1-8 Pokémon Zapdos
ru1-9 Pokémon Mewtwo
ru1-10 Pokémon Mew
ru1-11 Pokémon Diglett
ru1-12 Pokémon Lucario
ru1-13 Pokémon Skuntank
ru1-14 Pokémon Bastiodon
ru1-15 Pokémon Rattata
ru1-16 Pokémon Bibarel
dv1-18 Trainer Exp. Share
dv1-19 Trainer First Ticket
dv1-21 Pokémon Kyurem
xy0-1 Pokémon Weedle
xy0-2 Pokémon Pansage
xy0-3 Pokémon Chespin
xy0-4 Pokémon Quilladin
xy0-5 Pokémon Chesnaught
xy0-6 Pokémon Slugma
xy0-7 Pokémon Pansear
xy0-8 Pokémon Fennekin
xy0-9 Pokémon Braixen
xy0-10 Pokémon Delphox
xy0-11 Pokémon Panpour
xy0-12 Pokémon Froakie
xy0-13 Pokémon Frogadier
xy0-14 Pokémon Greninja
xy0-15 Pokémon Clauncher
xy0-16 Pokémon Poochyena
xy0-17 Pokémon Mightyena
xy0-18 Pokémon Inkay
xy0-19 Pokémon Pawniard
xy0-20 Pokémon Bisharp
xy0-21 Pokémon Honedge
xy0-22 Pokémon Snubbull
xy0-23 Pokémon Granbull
xy0-24 Pokémon Swirlix
xy0-25 Pokémon Farfetch'd
xy0-26 Pokémon Snorlax
xy0-27 Pokémon Miltank
xy0-28 Pokémon Skitty
xy0-29 Pokémon Bidoof
xy0-30 Pokémon Bunnelby
xy0-31 Pokémon Fletchling
xy0-32 Pokémon Furfrou
xy0-33 Pokémon Furfrou
xy0-34 Trainer Crushing Hammer
xy0-35 Trainer Poké Ball
xy0-36 Trainer Pokémon Catcher
xy0-37 Trainer Potion
xy0-38 Trainer Switch
xy0-39 Trainer Tierno

**Comment by CptSpaceToaster** [comment]
Please try to consider what you would like the rarities set or changed to in every case, before generating gobs of scripted output that bloats issues. If you think there really is an issue on all 77 cards sure (maybe make a new issue)... but the original issue was changing or adding an entry to a common card that was found in a pack. (a basic fighting energy)

You have listed every card that doesn't have a rarity, without considering the fact that some cards don't have a rarity that can be assigned to them.

**Comment by CptSpaceToaster** [comment]
After going through this myself, all of these cards probably shouldn't have rarity, except for the card listed in the OP.

- All cards in the `Southern Islands` - `si1`
    These cards were primarily released in two separate 9 card binders, and none of the cards have rarity symbols. https://bulbapedia.bulbagarden.net/wiki/Southern_Islands_(TCG)
- All cards in the `Pokémon Rumble` - `ru1`
    All 16 cards were released with the WiiWare game Pokémon Rumble, and do not have rarity markings. https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Rumble_(TCG)
- All cards in the  `Kalos Starter Set` -`xy0`
    The Kalos Starter Set is a set of three half decks that were given their own set numbers. Once again, the cards do not have rarity markings. https://bulbapedia.bulbagarden.net/wiki/Kalos_Starter_Set_(TCG)
- `dv1-18`, `dv1-19`, and `dv1-21` are interesting. 
    dv1-1 through dv-20 were released in 3 card Dragon's vault packs. I'm unsure what the distirbution rarity was, but I would assume it was a roughly equal distribution (implying that the cards have all of the same rarity... unless the 3 trainers were an exception). While most cards in Dragon Vault have the rarity `Rare Holo` in the API, I wouldn't be surprised if those rarities were added in error... and that the rarity from these cards should actually be removed. All of these cards do not have rarity markings from what I've seen.
- `dv1-21` is especially interesting, because it's numbered outside of the `dv1` set (21/20). It was released similar to a promo in the front of the `Dragon Majesty Special Collection: White Kyurem GX` box. I wouldn't have a clue what rarity this should be given.
