### ISSUE TITLE
Missing Sword & Shield Promos

### ISSUE THREAD

**Issue by pedrommcarrasco** [PokemonTCG/pokemon-tcg-data#182]
It looks like we're missing ~30 Promo cards from Sword & Shield and if we look into [Pokellector](https://www.pokellector.com/sets/SWSH-Sword-Shield-Promos) we can indeed confirm so.

What would be the best way to add these @adback03? - Since I'm unaware of how you track and populate the Database, I can't say if it's a bug or if we're just lacking data right now.

**Comment by adback03** [comment]
I should have some missing cards added shortly. Looks like 91 cards I've been able to find. These will be added to the repo soon.

**Comment by adback03** [comment]
I've added the missing promos I was able to pull with my tools. You can see them all here: https://pokemontcg.guru/set/swsh-black-star-promos/swshp

The repo has also been updated.

**Comment by pedrommcarrasco** [comment]
Thank you for such a quick response @adback03 🙇
