### ISSUE TITLE
Battle System (SWSH5)

### ISSUE THREAD

**Issue by lfgcampos** [PokemonTCG/pokemon-tcg-data#185]
Release day is today (March 19th).
https://tcg.pokemon.com/en-us/expansions/battle-styles/

ps: should we create tickets for every expansion just to track it?

**Comment by adback03** [comment]
Thanks! This has been added. Still waiting on hi-res images and some additional metadata, but the initial upload is complete. I'll keep this open until the rest of the data has been added.

**Comment by adback03** [comment]
This has been completed.
