### ISSUE TITLE
set.total not in line with number of cards returned by get all cards with set.id

### ISSUE THREAD

**Issue by SiWoC** [PokemonTCG/pokemon-tcg-data#189]
I would expect set.total would be the same, but for the following list it doesn't match:
set.id = total(printedTotal), cards.size()
ecard2 = 186(186), got 182 cards
ex3 = 97(97), got 100 cards
ex4 = 95(95), got 97 cards
ex5 = 101(101), got 102 cards
ex6 = 112(112), got 116 cards
ex7 = 109(109), got 111 cards
ex8 = 107(107), got 108 cards
ex9 = 106(106), got 107 cards
ex10 = 117(115), got 145 cards
dp7 = 103(100), got 106 cards
pl1 = 130(127), got 133 cards
pl2 = 114(111), got 120 cards
pl3 = 150(147), got 153 cards
pl4 = 99(99), got 111 cards
hgss1 = 123(123), got 124 cards
hgss2 = 95(95), got 96 cards
hgss3 = 90(90), got 91 cards
hgss4 = 102(102), got 103 cards
bw1 = 114(114), got 115 cards
dv1 = 20(20), got 21 cards
xyp = 183(183), got 216 cards
bw11 = 115(113), got 140 cards
xy2 = 109(106), got 110 cards
xy3 = 113(111), got 114 cards
xy4 = 119(119), got 124 cards
xy5 = 160(160), got 164 cards
xy6 = 110(108), got 112 cards
xy8 = 164(162), got 165 cards
xy9 = 123(122), got 126 cards
g1 = 115(115), got 117 cards
xy10 = 125(124), got 129 cards
xy12 = 109(108), got 113 cards
sm1 = 149(149), got 173 cards
smp = 156(156), got 247 cards
sm2 = 145(145), got 180 cards
sm3 = 147(147), got 177 cards
sm35 = 78(73), got 81 cards
sm4 = 111(111), got 126 cards
sm5 = 156(156), got 178 cards
sm6 = 146(131), got 150 cards
sm7 = 168(168), got 187 cards
sm75 = 78(70), got 80 cards
sm8 = 236(214), got 240 cards
sm9 = 196(181), got 198 cards
sm10 = 234(214), got 235 cards
sm11 = 258(236), got 260 cards
sm12 = 271(236), got 272 cards

totalSet: 13027
totalCards: 13406

24 differences in for example sm1 according to CptSpaceToaster@discord
Alternate: ['sm1-101a']
Rainbow: ['sm1-150', 'sm1-151', 'sm1-152', 'sm1-153', 'sm1-154', 'sm1-155', 'sm1-156', 'sm1-157']
Secrets:['sm1-158', 'sm1-159', 'sm1-160', 'sm1-161', 'sm1-162', 'sm1-163']
Basic Energy: ['sm1-164', 'sm1-165', 'sm1-166', 'sm1-167', 'sm1-168', 'sm1-169', 'sm1-170', 'sm1-171', 'sm1-172']

**Comment by CptSpaceToaster** [comment]
It seems like some sets are pretty trivial. We just didn't count the secret rares (as in `sm1`). The list seems to be much larger however... with so many of the sets being 1 or 2 cards "short", it would stand to reason that there might be a misunderstanding on what `total` should be indicating... Are there normally supposed to be cards in the list that aren't in the total?

**Comment by adback03** [comment]
I will have to go back and check these sets. `printedTotal` should be the number you actually see on the card, versus `total`, which is the actual number of cards found in the set, including secrets.

**Comment by adback03** [comment]
All totals should now reflect the number of cards correctly.
