### ISSUE TITLE
replace SWSH3 (Darkness Ablaze) error images with their fixed versions

### ISSUE THREAD

**Issue by jparanada** [PokemonTCG/pokemon-tcg-data#190]
Problem:
The original PTCGO release of Darkness Ablaze contains many errors on the images themselves. The most obvious are the faint vertical white streaks about one-third from the right of all V/VMAX cards. Other cards have horizontal white streaks, like DAA 18 and DAA 24.

Solution:
These images have since been fixed in PTCGO. You can find the fixed images at https://malie.io/static/listings/SWSH3.html , though not every card has changed. The complete list of card numbers that have changed is:

```
001
002
018
019
020
021
024
033
034
060
069
095
099
104
114
115
116
117
118
119
128
143
144
177
178
179
180
181
182
183
184
186
187
188
189
190
191
193
194
195
196
197
198
199
200
201
```

This is a request to replace the old images with the fixed versions.

**Comment by jparanada** [comment]
note: strangely, Salamence V DAA 185 is not fixed (and the current image still has the vertical line).

**Comment by adback03** [comment]
All images have been updated. This may take up to 24 hours to see the changes. Thanks!
