### ISSUE TITLE
Feature request - add regulation mark field to cards endpoint

### ISSUE THREAD

**Issue by bradley-erickson** [PokemonTCG/pokemon-tcg-data#193]
I would like to suggest adding a regulation mark field to the cards portion of the API. TPCI introduced the regulation mark with the Sword and Shield sets to help with rotation. Prior to this, cards were rotated in and out of expanded based on set. This is still mostly the case; however, there exists some weird cases. Sordward & Shielbert from Battle Styles has the 'D' regulation mark and all other cards in the Battle Styles set contain the 'E' regulation mark. This won't be a problem for another year when they likely rotate the standard format to 'E' and presumably 'F' regulation marks.
Here is some more information on how they are handling rotation.
https://www.pokemon.com/us/pokemon-news/2022-pokemon-tcg-championship-series-season-format-rotation/

**Comment by Jake-Gearhart** [comment]
In addition to adding regulation marks for Sword & Shield cards, it would be nice to have them for the Sun & Moon cards which began with regulation mark A in Japan even though the cards don't have the marks printed directly on them.

**Comment by adback03** [comment]
Good idea, I will plan on adding this new field before the next rotation.

**Comment by adback03** [comment]
`regulationMark` has now been added and will be included for Sword and Shield and sets going forward.
