### ISSUE TITLE
Black Star Promos SWSH075 and onward missing from database.

### ISSUE THREAD

**Issue by TheCharmaster** [PokemonTCG/pokemon-tcg-data#196]

**Comment by adback03** [comment]
These were updated a couple weeks ago.

**Comment by TheCharmaster** [comment]
I don't see them.  I'm in Cube Koga, which uses this database, and I looked up several of the Promos in question and don't see them.  So I am afraid that this issue is still not closed (unless there is something wrong with Cube Koga).
