### ISSUE TITLE
Ultra Prism - Update Rarity Field

### ISSUE THREAD

**Issue by adback03** [PokemonTCG/pokemon-tcg-data#20]
The rarity field on all Ultra Prism cards needs to get filled out.

Please comment here if you pick this up so multiple people don't start this and waste their time.

**Comment by r0adkll** [comment]
I'll help with this as soon as I finish my current edit of XY Black Star Promos

**Comment by adback03** [comment]
These rarities and secret rares have been added.

**Comment by r0adkll** [comment]
@adback03 It looks like the Rainbow Rare GX pokemon are still missing from the set

**Comment by r0adkll** [comment]
nvm, it was a bug in my implementation. Looks great!
