### ISSUE TITLE
Black Star Promo Charizard SM158 TCG Player link points to incorrect card

### ISSUE THREAD

**Issue by jyang619** [PokemonTCG/pokemon-tcg-data#204]
The Charizard SM158 links to the staff version (https://www.tcgplayer.com/product/183967/pokemon-sm-promos-charizard-sm158-staff) rather than the normal card (https://www.tcgplayer.com/product/183966/pokemon-sm-promos-charizard-sm158)

**Comment by adback03** [comment]
Thanks, this has been fixed.
