### ISSUE TITLE
Black Star Promos SWSH075 and onward STILL missing from database (see #196), even though the issue was closed.

### ISSUE THREAD

**Issue by TheCharmaster** [PokemonTCG/pokemon-tcg-data#206]
I still can't find any of these PROMOs in the database, although the issue was closed eight days ago and I was told that they were updated a few weeks ago.

**Comment by MatiasOETamminen** [comment]
Please see for yourself: https://raw.githubusercontent.com/PokemonTCG/pokemon-tcg-data/master/cards/en/swshp.json
The issue is with the client, not with the database

**Comment by adback03** [comment]
SWSH075 doesn't exist, but promos after that are there. Not sure where you are looking, but you can see them all here: https://pokemontcg.guru/set/swsh-black-star-promos/swshp
