### ISSUE TITLE
Reprint legalities

### ISSUE THREAD

**Issue by MatiasOETamminen** [PokemonTCG/pokemon-tcg-data#208]
Now that card legalities are a parameter of a card, we should have old reprinted cards reflect their actual legality.
Here's two lists of those, for standard and expanded respectively:
https://pokegym.net/index.php/current-standard-legal-card-list/
https://pokegym.net/index.php/current-expanded-legal-card-list/

**Comment by adback03** [comment]
Per #214, closing this. Will need to revisit at time of rotation, and determine a better way to keep this list up to date.
