### ISSUE TITLE
Next version : support openapi

### ISSUE THREAD

**Issue by HumanG33k** [PokemonTCG/pokemon-tcg-data#211]
It can be great for the next iteration of the api to support : openapi specification. 
https://www.openapis.org/

In that way it will be easy to generate server and cli for the api.
https://openapi-generator.tech/

thx for your work.

**Comment by adback03** [comment]
Thanks for the suggestion! As a v3 is a long ways out, I'm going to close this issue and add it to my internal list of suggestions. Thank you.
