### ISSUE TITLE
Evolving Skies (SWSH7)

### ISSUE THREAD

**Issue by lfgcampos** [PokemonTCG/pokemon-tcg-data#215]
Release is this week (August 27th).
https://tcg.pokemon.com/en-us/expansions/evolving-skies/

**Comment by aprct** [comment]
Looking forward to the update!

**Comment by MapleMaelstrom** [comment]
It's available on API, json data will hopefully be.added to github soon

**Comment by adback03** [comment]
Thanks for the patience all, JSON data has been added to github as well.
