### ISSUE TITLE
SWSH promos have fallen behind

### ISSUE THREAD

**Issue by MatiasOETamminen** [PokemonTCG/pokemon-tcg-data#227]
SWSH promos number SWSH132–SWSH167 are missing. I'm not exactly sure about the release dates, but at least the V-UNIONs are out already. In my opinion, having the V-UNIONs and the other Celebrations-related promos added is a priority, since they're relevant right now.

**Comment by adback03** [comment]
Added a bunch of missing promos today. Should hopefully be caught up now.
