### ISSUE TITLE
POP series 6 #13 (cherubi) and #17 (turtwig) have no hi-res images.

### ISSUE THREAD

**Issue by Pepper0ni** [PokemonTCG/pokemon-tcg-data#231]
When I attempt to load the image links listed in the API for the large versions of these cards, both in a program and directly in browser, I receive a card back instead. lo res seems to work perfectly fine and I have had other people replicate the issue.

**Comment by adback03** [comment]
These have been added. It may be a 24h delay until you can see the changes.
