### ISSUE TITLE
API Error: Using a range filter on `nationalPokedexNumbers` causes most of the Tag Team Cards to be returned in the results.

### ISSUE THREAD

**Issue by CptSpaceToaster** [PokemonTCG/pokemon-tcg-data#233]
`GET` `/cards?q=nationalPokedexNumbers:[1 TO 1]` returns every Bulbasaur ✅ 
`GET` `/cards?q=nationalPokedexNumbers:[3 TO 3]` returns every Venusaur (including the tag teams) ✅ 
`GET` `/cards?q=nationalPokedexNumbers:[4 TO 4]` returns every Charmander **AND** every Tag Team that includes Venusaur 💥  

It seems that as long as you pick a number to iterate through, that's _contained_ between the upper and lower bound of the numbers found in the tag team... then the tag team will show up as a part of the result in error.

If you iterate over a range, as in `[387 TO 493]` the problem seems to strike as there are many tag-team cards that envelope numbers `387 TO 493` that _aren't_ actually in the range, however the problem is best viewed with a targeted sample `4 TO 4`

**Comment by adback03** [comment]
I spent some time digging into this last night, and I think I know the issue. Will try to get this resolved soon.

**Comment by adback03** [comment]
This should now be resolved.

https://pokemontcg.guru/search?q=np%3A%5B4+to+4%5D
https://pokemontcg.guru/search?q=np%3A%5B3+to+4%5D
