### ISSUE TITLE
Legality attributes of sets in the era of regulation markings

### ISSUE THREAD

**Issue by MatiasOETamminen** [PokemonTCG/pokemon-tcg-data#245]
Starting from swsh1, the legality of cards is no longer defined by the card belonging to a legal set but by the regulation markings. The regulation marking boundaries roughly follow set boundaries, but not 100%. Pre-SWSH expanded cards probably continue to be defined as expanded-legal by set attribution, and the regulation markings probably all remain expanded-legal (so even the SWSH block sets could be said to be expanded-legal), but the main issue is with sets being "standard-legal" when it's only defined on a card-by-card basis. How should the data structure reflect this?

See Tournament Rules Handbook, section 5.4.1.1: https://assets.pokemon.com//assets/cms2/pdf/play-pokemon/rules/play-pokemon-tournament-rules-handbook-09302021-en.pdf

**Comment by MatiasOETamminen** [comment]
Closely related to #193

**Comment by adback03** [comment]
I think each each will be updated to have a `regulationMark` field, and the set legality will still have to remain more generic for backwards compatibility. So even if some cards aren't legal in a set, but many cards are, the set would still be marked as legal.

However, individual card legality will always trump set legality.

Thoughts?

**Comment by adback03** [comment]
A `regulationMark` field has been added to better reflect legality for cards moving forward. The legalities section will still be supported on a set basis, but as more of a generalization/quick overview.
