### ISSUE TITLE
SM Black Star Promos (smp) prerelease cards TCGPlayer link to staff prerelease

### ISSUE THREAD

**Issue by ushmau5** [PokemonTCG/pokemon-tcg-data#263]
Been noticed for many of the prerelease cards in the SM Black Star Promos set (smp) that the TCGPlayer prices are coming from the Staff version of the cards.

I'l try to list as many examples below as I can find;
- Wash Rotom: https://prices.pokemontcg.io/tcgplayer/smp-SM94
- Phione: https://prices.pokemontcg.io/tcgplayer/smp-SM220
- Seviper: https://prices.pokemontcg.io/tcgplayer/smp-SM46

There are loads more I would be here all day, I would re-check all of the pre-release cards in this set as there is possibly a flaw in the logic assigning the url's to them.

**Comment by ushmau5** [comment]
This bug is the same with SWSH Black Star Promos, is this intended behaviour?

**Comment by pedrommcarrasco** [comment]
The same applies to this [Charizard](https://pokemontcg.guru/card/charizard-sword-and-shield/swshp-SWSH066) - it should be showing this [prices](https://www.tcgplayer.com/product/224365/pokemon-swsh-sword-and-shield-promo-cards-charizard-swsh066-prerelease-promo?xid=pib466da82-9798-447a-a0d8-3428cf10ff29&page=1&Language=English) but shows [these](https://www.tcgplayer.com/product/224366/pokemon-swsh-sword-and-shield-promo-cards-charizard-swsh066-prerelease-promo-staff?xid=pib466da82-9798-447a-a0d8-3428cf10ff29&page=1&Language=English) instead.

**Comment by adback03** [comment]
I believe I have resolved all these issues across the various promo sets. If you spot any more, feel free to open a new issue.
