### ISSUE TITLE
Pokemon SP updates

### ISSUE THREAD

**Issue by mmxxiii** [PokemonTCG/pokemon-tcg-data#27]
I am going to fix all of the pokemon SP names (e.g. "Dialga G", "Lucario GL", "Gallade 4", etc.), but while I'm at it, I'd like to add a "Pokemon SP" tag to the cards, but I'm not sure where it should go.

I was thinking about putting it in the "text" field, but perhaps a new field called "tags", which contains an array of these values?

This field could also be used for "Team Plasma", "Ultra Beast", and any other special tags which are referenced in other card's text but aren't part of the pokemon's name.

It could also be used for "Pokemon EX" and "Pokemon GX" so that we can get that data out of the "subtype" field, and use the subtype field for the pokemon's stage (since we can't currently search for stage-2 GX Pokemon)

**Comment by adback03** [comment]
Dang, just saw this. I went through earlier today and cleaned up some of the SP names myself.

As far as the tags, I know one proposal was to support multiple subtypes, something like `['Stage 2', 'GX']`. Thoughts?

**Comment by mmxxiii** [comment]
Making subtypes into an array containing multiple subtypes would work, but that would also break some applications which are using the api currently as they are expecting subtype to be string.
I think adding a separate array field which contains "extra" tags would be an easier transition.
Keeping the pokemon's stage in subtype makes sense, as no pokemon have more than 1 stage. This would of course mean going through and setting all EXs to Basic (or MEGA), and adding the stage for all GXs.

**Comment by adback03** [comment]
Yeah, I wouldn't just change the current subtype field. More realistically, I'd switch over to a `v2` version of the API within the coming months that would have these enhancements. There are a few other breaking changes that would get added at that point as well. Any decision right now affecting `v1` has to be backwards compatible.

**Comment by mmxxiii** [comment]
Here is the previous discussion of the EX/Basic issue. Just dropping it here for reference.

https://github.com/PokemonTCG/pokemon-tcg-api/issues/40

**Comment by adback03** [comment]
Subtypes has been introduced as part of V2, and the names of the SP cards are also fixed.
