### ISSUE TITLE
No TCGPlayer prices for Legendary Treasures Radiant Collection

### ISSUE THREAD

**Issue by ushmau5** [PokemonTCG/pokemon-tcg-data#270]
Legendary Treasures with setCode `bw11` has no TCGPlayer prices for cards with `RC` in the number.

These cards are part of the Radiant Collection.

Here are the card lists on PSA.

Legendary Treasures: https://www.psacard.com/auctionprices/tcg-cards/2013-pokemon-black-white-legendary-treasures/116903
Legendary Treasures Radiant Collection: https://www.psacard.com/auctionprices/tcg-cards/2013-pokemon-black-white-legendary-treasures-radiant-collection/118232

**Comment by adback03** [comment]
This has been resolved.
