### ISSUE TITLE
No prices for Breakpoint (xy9) alternative arts

### ISSUE THREAD

**Issue by ushmau5** [PokemonTCG/pokemon-tcg-data#272]
There are no prices for the following cards in the following set;

Breakpoint- xy9

98a - Delinquent
98b - Delinquent
107a - Professor Sycamore

**Comment by adback03** [comment]
This has been resolved:

https://pokemontcg.guru/card/delinquent-xy/xy9-98a
https://pokemontcg.guru/card/delinquent-xy/xy9-98b
https://pokemontcg.guru/card/professor-sycamore-xy/xy9-107a
