### ISSUE TITLE
Legendary Treasures

### ISSUE THREAD

**Issue by Nirvanna21** [PokemonTCG/pokemon-tcg-data#286]
Legendary Treasures should be treated as a set and subset, much like Brilliant Stars and Brilliant Stars Trainer Gallery.

The subset known as Radiant Collection consists of 25 cards. Please apply this change, as currently when you pull the Legendary Treasures data it will share set position numbers for the first 25 cards.

**Comment by Pepper0ni** [comment]
The API uses the same definition of set as pokemon.com's search, which does not list that set has having a distinct subset.

Yes it's inconsistent. Blame TCPI.

https://discord.com/channels/222559292497068043/856810388247281686/942936550528917534

Issue should be closed as Won't fix.

**Comment by adback03** [comment]
Perpper0ni is right, this API follows the collection rules of Pokemon.com.
