### ISSUE TITLE
Lost Origin set is missing

### ISSUE THREAD

**Issue by stebaker92** [PokemonTCG/pokemon-tcg-data#312]
Lost Origin, otherwise known as swsh11 was released today (9/9/2022) but there's no set or card data as far as I can see and no issues/pull requests open yet 
Details are available on the Pokémon website:.
https://tcg.pokemon.com/en-us/expansions/lost-origin/
 
Also see cardmarket:
https://www.cardmarket.com/en/Pokemon/Products/Singles/Lost-Origin?idRarity=0

**Comment by adback03** [comment]
This has been released!
