### ISSUE TITLE
2023 Standard Rotation Legality Updates

### ISSUE THREAD

**Issue by JayHors** [PokemonTCG/pokemon-tcg-data#409]
Currently, the API is out-of-sync with the current standard format. This issue's goal is to track progress towards updating the `legalities` fields for cards. 
https://pokegym.net/current-standard-legal-card-list/ is what I'll be basing changes off of, but I'll be watching for ones missed by PokeGym.

**Comment by adback03** [comment]
Thanks! All PRs have been merged.
