### ISSUE TITLE
Dragon Majesty - Update Rarity Field

### ISSUE THREAD

**Issue by lfgcampos** [PokemonTCG/pokemon-tcg-data#42]
The rarity field on all Dragon Majesty cards needs to get filled out.

ex: https://github.com/PokemonTCG/pokemon-tcg-data/blob/master/json/cards/Dragon%20Majesty.json#L16

**Comment by starg09** [comment]
Just as an update, I just made a pull request adding this info ( #43 ) 🙂

**Comment by lfgcampos** [comment]
Thanks for the update!!

**Comment by adback03** [comment]
This has been released. Thanks all.
