### ISSUE TITLE
Create "ex", "EX", "ex" and "Tera ex" distinctions in subtype.

### ISSUE THREAD

**Issue by LeviSnoot** [PokemonTCG/pokemon-tcg-data#437]
So, with SV1 we see the resurfacing of ex cards. This creates a bit of confusion in the API since "ex" and "EX" cards have existed in the past, and each iteration has different rules. This was pointed out in #412 by @Cealgair since `svp` has a subtype of `ex-3` in the API, and neither of us are sure what it means.

My suggestion is making each ex iteration distinct. That way users can match the type of ex correctly. 

I suggest doing something like this (though I'm sure smarter people can think of something way better):

![image](https://github.com/PokemonTCG/pokemon-tcg-data/assets/13402525/fcf4f770-ec3f-4250-9c58-7409536ae4e8)
`ex1-96`

```json
{
  "data": {
    "subtypes": [
      "Basic",
      "ex"
    ]
}
```

![image](https://github.com/PokemonTCG/pokemon-tcg-data/assets/13402525/90334434-7fac-4a7b-bdde-3fb467a93774)
`bwp-BW37`

```json
{
  "data": {
    "subtypes": [
      "Basic",
      "EX"
    ]
}
```

![image](https://github.com/PokemonTCG/pokemon-tcg-data/assets/13402525/6eefe94e-f628-4cbb-b6eb-9e116beb7381)
`sv1-19`

```json
{
  "data": {
    "subtypes": [
      "Stage 1",
      "ex-1"
    ]
}
```

![image](https://github.com/PokemonTCG/pokemon-tcg-data/assets/13402525/3c49daa4-c27b-42a9-b9e2-35cec64f2d1d)
`sv1-32`

```json
{
  "data": {
    "subtypes": [
      "Stage 1",
      "Tera ex"
    ]
}
```

The user of the API can parse the string however they like in their code but if there are conflicts (such as with `ex1-96` and `bwp-BW37`), there's no way to intuitively know which card is what type of ex.

**Comment by Pepper0ni** [comment]
According to PKMNCards discord gen 3 ex and new ex are the same mechanic for rulings purposes, so should use the same subtype.

I would also request that "Tera" is a subtype separate from ex, as Tera ex's are still exs and there's a chance that they release non-ex tera in the future.

**Comment by LeviSnoot** [comment]
> According to PKMNCards discord gen 3 ex and new ex are the same mechanic for rulings purposes, so should use the same subtype.

You're right, I had misread the SV1 player's guide. That being said their icons are still different so I think the distinction is warranted, for example with databases that have conditionals for icons.

> I would also request that "Tera" is a subtype separate from ex, as Tera ex's are still exs and there's a chance that they release non-ex tera in the future.

Same thing here, the icon is different, as shown below:

![ex_badge](https://github.com/PokemonTCG/pokemon-tcg-data/assets/13402525/a1325f1c-eee9-4d55-8425-01b8fad7d7a5)

![ex_tera_badge](https://github.com/PokemonTCG/pokemon-tcg-data/assets/13402525/fd665db7-ec37-4d56-92ca-27e7ef95ead4)

**Comment by adback03** [comment]
I think keeping Tera separate still makes sense, but I support a separate EX vs ex subtype. We'd have to go back to these sets and update accordingly. Pokemon.com also separates EX and ex subtypes.

**Comment by Cealgair** [comment]
> > I would also request that "Tera" is a subtype separate from ex, as Tera ex's are still exs and there's a chance that they release non-ex tera in the future.
> 
> Same thing here, the icon is different

By that logic we should have separate subtypes for "GX", "GX Ultra Beast", "TAG TEAM GX" and "TAG TEAM GX Ultra Beast", which to me doesn't seem sensible when all of them are Pokémon-GX anyway and we can have separate subtypes for TAG TEAM and Ultra Beast. So I think how Tera Pokémon are handled is fine as it is after #436 was merged.

> According to PKMNCards discord gen 3 ex and new ex are the same mechanic for rulings purposes, so should use the same subtype.

Didn't they rule that Pokémon-ex (from the ex era) do not "have a rule box" while Pokémon ex (from sv) do? I'm not necessarily against using "ex" as the subtype for both but I believe there are some differences

**Comment by LeviSnoot** [comment]
> By that logic we should have separate subtypes for "GX", "GX Ultra Beast", "TAG TEAM GX" and "TAG TEAM GX Ultra Beast", which to me doesn't seem sensible when all of them are Pokémon-GX anyway and we can have separate subtypes for TAG TEAM and Ultra Beast. So I think how Tera Pokémon are handled is fine as it is after #436 was merged.

After looking at that commit it makes sense, you can have a condition that matches both Tera and ex to do what I'm describing, so that's fine. The Pokémon-ex and ex I'm not sure about, I guess you could have a condition that matches for cards that were released before/after a certain date but idk feels like it should be simpler than that.

**Comment by Cealgair** [comment]
> I guess you could have a condition that matches for cards that were released before/after a certain date but idk feels like it should be simpler than that.

At the moment the API doesn't have a way to do case-sensitive matching (unless I'm missing something) (see issue above), so using that there's not even a way to differentiate "ex" from "EX" by just looking at the subtype. The release date wouldn't work 100% either because of the Celebration Classic Collection (cel25c). Right now as far as I know the "best" way to distinguish them with API queries is:
* Pokémon-ex: `rules:"When Pokémon-ex has been Knocked Out, your opponent takes 2 Prize cards."`
* Pokémon-EX: `rules:"Pokémon-EX rule: When a Pokémon-EX has been Knocked Out, your opponent takes 2 Prize cards."`
* Pokémon ex: `rules:"Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards."`

Or I guess even better:
* Pokémon-ex: `rules:"When Pokémon-ex"`
* Pokémon-EX: `rules:"Pokémon-EX rule"`
* Pokémon ex: `rules:"Pokémon ex rule"`

**Comment by Cealgair** [comment]
This issue has been open for a while. Do we all agree that "ex" should be the subtype for Pokémon-ex (from the ex era) and for Pokémon ex (from sv), that "EX" should be the subtype for Pokémon-EX (from bw/xy), and that "Tera" should be a separate subtype like it is now in sv1 and sv2?

**Comment by LeviSnoot** [comment]
I'm all for it so that makes two of us, if we're unanimous I'll get right on updating #412

**Comment by LeviSnoot** [comment]
Closing this as I feel like we've reached a conclusion, I've also updated #412 so it should be ready for merge. Feel free to re-open if necessary.
