### ISSUE TITLE
SM100 Lucario-GX promo is missing it's image

### ISSUE THREAD

**Issue by r0adkll** [PokemonTCG/pokemon-tcg-data#46]
https://pokemontcg.io/cards/smp-SM100

**Comment by r0adkll** [comment]
I will also note that several of the Promos are missing their images

**Comment by adback03** [comment]
This image has been added. I also added in some other missing promo images:

SM100, SM101, SM102, SM105, SM106, SM107, SM110, SM111, SM112, SM113, SM114

**Comment by adback03** [comment]
annnnd SM108 and SM109.

**Comment by r0adkll** [comment]
It still looks like the lucario-gx promo is missing it's lo-res image
