### ISSUE TITLE
Way to filter all cards that have rules

### ISSUE THREAD

**Issue by jtodd3** [PokemonTCG/pokemon-tcg-data#518]
I'm looking to make a `/search` request that does not return cards that have a `rules` property.

Any help would be appreciated, Thanks!

**Comment by Cealgair** [comment]
https://api.pokemontcg.io/v2/cards?q=-rules:*
Is this what you need?

**Comment by jtodd3** [comment]
What would it look like if I wanted to filter out specific rules. ie) Tag Team, V, or ex?

**Comment by jtodd3** [comment]
nevermind, I was able to do what I was looking for by filtering on subtypes
