### ISSUE TITLE
Missing json

### ISSUE THREAD

**Issue by arki23** [PokemonTCG/pokemon-tcg-data#52]
I can't find the file for:
https://api.pokemontcg.io/v1/cards/ex3-98 - Charmander 98/97
https://api.pokemontcg.io/v1/cards/ex3-99 - Charmeleon 99/97
https://api.pokemontcg.io/v1/cards/ex3-100 - Charizard 100/97
https://api.pokemontcg.io/v1/cards/ex4-96 - Absol 96/95
https://api.pokemontcg.io/v1/cards/ex4-97 - Jirachi 97/95
https://api.pokemontcg.io/v1/cards/ex5-102 - Groudon 102/101
https://api.pokemontcg.io/v1/cards/ex6-113 - Charmander 113/112
https://api.pokemontcg.io/v1/cards/ex6-114 - Articuno ex 114/112
https://api.pokemontcg.io/v1/cards/ex6-115 - Moltres ex 115/112
https://api.pokemontcg.io/v1/cards/ex6-116 - Zapdos ex 116/112
https://api.pokemontcg.io/v1/cards/ex7-110 - Charmeleon 110/109
https://api.pokemontcg.io/v1/cards/ex7-111 - Here Comes Team Rocket! 111/109
https://api.pokemontcg.io/v1/cards/ex8-108 - Raikou ex 108/107
https://api.pokemontcg.io/v1/cards/ex9-107 - Farfetch'd 107/106
https://api.pokemontcg.io/v1/cards/bw1-115 - Pikachu 115/114
https://api.pokemontcg.io/v1/cards/bw4-101 - Chandelure 101/99
https://api.pokemontcg.io/v1/cards/bw4-102 - Zoroark 102/99
https://api.pokemontcg.io/v1/cards/bw4-103 - Hydreigon 103/99
https://api.pokemontcg.io/v1/cards/dv1-21 - Kyurem 21/20
https://api.pokemontcg.io/v1/cards/xyp-XY162 - Greninja XY162
https://api.pokemontcg.io/v1/cards/xyp-XY163 - Weezing XY163
https://api.pokemontcg.io/v1/cards/xyp-XY166 - M Gengar EX XY166
https://api.pokemontcg.io/v1/cards/xyp-XY179 - Snorlax XY179
https://api.pokemontcg.io/v1/cards/xyp-XY180 - Arcanine BREAK XY180
https://api.pokemontcg.io/v1/cards/xyp-XY182 - Mandibuzz BREAK XY182
https://api.pokemontcg.io/v1/cards/xy4-120 - M Manectric EX 120/119
https://api.pokemontcg.io/v1/cards/xy4-121 - M Gengar EX 121/119
https://api.pokemontcg.io/v1/cards/xy4-122 - Dialga EX 122/119
https://api.pokemontcg.io/v1/cards/xy5-161 - Dive Ball 161/160
https://api.pokemontcg.io/v1/cards/xy5-162 - Enhanced Hammer 162/160
https://api.pokemontcg.io/v1/cards/xy5-163 - Switch 163/160
https://api.pokemontcg.io/v1/cards/xy5-164 - Weakness Policy 164/160
https://api.pokemontcg.io/v1/cards/xy12-110 - Flying Pikachu 110/108
https://api.pokemontcg.io/v1/cards/xy12-111 - Surfing Pikachu 111/108
https://api.pokemontcg.io/v1/cards/xy12-112 - Imakuni?'s Doduo 112/108
https://api.pokemontcg.io/v1/cards/xy12-113 - Here Comes Team Rocket 113/108
https://api.pokemontcg.io/v1/cards/smp-SM103 - Lunala-GX SM103
https://api.pokemontcg.io/v1/cards/smp-SM104 - Solgaleo-GX SM104
https://api.pokemontcg.io/v1/cards/sm6-143 - Energy Recycler 143/131
 

Check either if the "imageUrlHiRes" exists!

**Comment by rastoAtGit** [comment]
many more cards from 'smp' set are missing i think:
smp-SM126
smp-SM137
smp-SM138
smp-SM139
smp-SM140
smp-SM141
smp-SM142
smp-SM143
smp-SM144
smp-SM145
smp-SM148
smp-SM150
smp-SM151
smp-SM152 
smp-SM153 
smp-SM154  
smp-SM157

**Comment by supasheva** [comment]
Hello. I wanted to help with this issue. Is there a specific way the images for example should be?

**Comment by marcoescher** [comment]
Hi @supasheva, I think the repository doesn't have a fixed standard.

For the most recent sets, normal images are usually pulled from Pokemon.com in a 245x342 format (0.716, which reflects the aspect ratio of the physical card) and hi-res images from Pkmncards.com in a 700x990 format (0.707).

Older sets images have been pulled from various sources (mostly Pkmncards.com), but in a wide range of sizes and aspect ratios.

**Comment by supasheva** [comment]
That sounds cool. I will fork the repo, add to it and make a PR if that is ok with you guys.

**Comment by marcoescher** [comment]
Sorry @supasheva, beat you to it :-)
Scans are still missing though. Can you collect and upload them somewhere with the correct folder structure, so that @adback03 can do the rest?

**Comment by supasheva** [comment]
Ah yeah sure. Like a dropbox or something?

**Comment by adback03** [comment]
Thanks everyone. These cards + all images have been uploaded.

**Comment by lfgcampos** [comment]
@adback03 I feel like last release with changes from this PR didn't update the `updatedAt` field.
Can you check it and if I am wrong, tell me when/how do you update it?

This is the field I use on my project to check which sets I need to update.

**Comment by adback03** [comment]
@lfgcampos sorry about that, they should be updated now.

https://api.pokemontcg.io/v1/sets?updatedSince=01/06/2019
