### ISSUE TITLE
are PAF inside?

### ISSUE THREAD

**Issue by miguelgargallo** [PokemonTCG/pokemon-tcg-data#526]
I cannot find the Jirachi and Doublade

**Comment by Cealgair** [comment]
Yes, Paldean Fates has been added to this API, with the id `sv4pt5`. That set does not contain any Jirachi or Doublade. Did you mean PAR? Paradox Rift was also added, with the id `sv4`

**Comment by miguelgargallo** [comment]
let me check on db, thanks for your feedback, honestly so fast

**Comment by miguelgargallo** [comment]
okay I spent the sat and sun studying the set, i got 17443 cards, how many are there?

**Comment by Cealgair** [comment]
17438 is the current total number of cards. In general, if you make an api query, it will return a number called `"totalCount"` which tells you how many cards match your query. For example, if your query is `set.id:swshp` to get all Sword&Shield promos, the total count will be 304.

This is the url related to my example: https://api.pokemontcg.io/v2/cards?q=set.id:swshp

This is the url from which I got the total number of cards: https://api.pokemontcg.io/v2/cards

Here is the documentation if you need help understanding the queries https://docs.pokemontcg.io/

**Comment by miguelgargallo** [comment]
Then so, I do not understand this

https://github.com/tcgdex/cards-database

![image](https://github.com/PokemonTCG/pokemon-tcg-data/assets/5947268/333947ec-febc-46f7-aa4a-58a4ff6ef713)

**Comment by Cealgair** [comment]
It's likely that tcgdex doesn't use the Pokémon TCG API database directly. In particular, I see they have all trainer kits, while this database does not (see #316 )

If you have issues with the tcgdex card database, you should open them on https://github.com/tcgdex/cards-database/issues

**Comment by miguelgargallo** [comment]
Great, thanks to clarify, sounds ok, have a nice weekend
