### ISSUE TITLE
Trick or Trade sets missing

### ISSUE THREAD

**Issue by b-onc** [PokemonTCG/pokemon-tcg-data#569]
Apologizes if this has been discussed, I could not find a closed issue/PR.

Trick or Trade sets (2022, 2023, 2024, any of them) are missing. I wonder if this is on purpose (most likely) and if so, is it up to discussion? I believe they should be included since McDonalds sets are included - those are reprints too.

**Comment by Cealgair** [comment]
Cards in McDonalds sets do have their own card number and set symbol, I believe that's the reason why they were included in the API. Other than the Celebrations Classic Collection, I don't think this API will support reprints with the same card number and set symbol, at least not in its current version (v2)

**Comment by b-onc** [comment]
Clear enough, thank you!
