### ISSUE TITLE
Filtering not working at all

### ISSUE THREAD

**Issue by ewalk40** [PokemonTCG/pokemon-tcg-data#572]
I have tried GET, I have tried Curl GET and no matter what if I try, for example, 

https://api.pokemontcg.io/v2/cards?name=pikachu

with my API key as a header, it just returns the first 250 of all the possible cards, am I not doing something correctly with formatting? I am overly confused.

**Comment by Cealgair** [comment]
https://api.pokemontcg.io/v2/cards?q=name:pikachu is what you're looking for

**Comment by ewalk40** [comment]
So would this be right?
https://api.pokemontcg.io/v2/cards?set.id:sv8

**Comment by Cealgair** [comment]
https://api.pokemontcg.io/v2/cards?q=set.id:sv8

You're missing `q=` after the question mark

**Comment by ewalk40** [comment]
The issue can be deleted, thank you Cealgair! Sorry for the hassel! Have a good one!

**Comment by Cealgair** [comment]
No worries. Issues on GitHub cannot be deleted, however you should see a button below to close it
