### ISSUE TITLE
Wrong images for SMP

### ISSUE THREAD

**Issue by lfgcampos** [PokemonTCG/pokemon-tcg-data#72]
I've found some of the images are not correct on SMP cards.
Open the `imageUrl` or `imageUrlHiRes` and you will see Articuno instead of Zapdos.
```
"id": "smp-SM145",
      "name": "Zapdos",
      "nationalPokedexNumber": 145,
      "imageUrl": "https://images.pokemontcg.io/smp/SM145.png",
      "imageUrlHiRes": "https://images.pokemontcg.io/smp/SM145_hires.png",
...
```

**Comment by adback03** [comment]
This has been fixed - it may took a bit to see the changes propagate.
