### ISSUE TITLE
Missing ConvertedRetreatCosts in SM9?

### ISSUE THREAD

**Issue by pylonsarenice** [PokemonTCG/pokemon-tcg-data#80]
Hi all, I'm new to this but I noticed that some SM9 cards without retreat costs e.g. https://pokemontcg.io/cards/sm9-46 don't have convertedRetreatCost defined whereas in SM8 these values were set to zero e.g.  https://pokemontcg.io/cards/sm8-146 

Thanks for the great tool!

**Comment by adback03** [comment]
Thanks for the info! In general, I'm trying to standardize on no converted retreat cost if there is no retreatCost specified. In the future, this is how you can expect the data to look. I will try to go look at past sets and see what needs to be cleaned up.

**Comment by pylonsarenice** [comment]
Great, thanks Andrew!
