### ISSUE TITLE
Dataset for theme decks

### ISSUE THREAD

**Issue by Monbrey** [PokemonTCG/pokemon-tcg-data#87]
I'm using this API for a project I'm working on and was looking for a way to also track the theme decks. I've started building the dataset myself, figured I'd post here and see if there's any interest in it being PR'd when I'm done. No idea when that will be though.

The data model I'm using looks roughly like this - open to feedback and any information others might also want to see. The id naming convention is also open to change, I just picked something unique.

```json
[
    {
        "id": "d-base1-1",
        "name": "Overgrowth",
        "cards": [
            { "id": "base1-44", "count": 4 },
            { "id": "base1-30", "count": 2 },
            { "id": "base1-69", "count": 4 },
            { "id": "base1-33", "count": 2 },
            { "id": "base1-17", "count": 1 },
            { "id": "base1-65", "count": 4 },
            { "id": "base1-64", "count": 3 },
            { "id": "base1-35", "count": 2 },
            { "id": "base1-6", "count": 1 },
            { "id": "base1-91", "count": 2 },
            { "id": "base1-93", "count": 2 },
            { "id": "base1-94", "count": 1 },
            { "id": "base1-90", "count": 2 },
            { "id": "base1-95", "count": 2 },
            { "id": "base1-99", "count": 16 },
            { "id": "base1-102", "count": 12 }
        ]
    }
]
```

**Comment by adback03** [comment]
Good idea! I could see people having an interest in this data. I assume your ID convention is something like this?

`d-<set id>-<deck number>`?

Seems reasonable to me.

**Comment by Monbrey** [comment]
Yeah that naming convention is the idea, based on the existing conventions for sets/cards but with the `d-` flag

**Comment by r0adkll** [comment]
Bump! This would be great

**Comment by xxninjabunnyxx** [comment]
I would be happy to help.
