### ISSUE TITLE
Free energy is represented with a Fire symbol

### ISSUE THREAD

**Issue by CptSpaceToaster** [PokemonTCG/pokemon-tcg-data#95]
Probably need a new picture for Free energy so that cards that have attacks that are "Free" don't end up using the symbol for a fire energy:

https://pokemontcg.io/cards/sm2-21

**Comment by adback03** [comment]
I think "Free" shouldn't even be there. If it is free, it should be an empty array. Will still need to fix though.

**Comment by joergl87** [comment]
I guess "Free" should be called "Blank". And I think it schould be there. They call it explicitly “blank” Energy in this sentence on following link. "Some Alolan Pokémon have attack costs that show “blank” Energy symbols, meaning that they have no attack cost." 
[Here](https://www.pokemon.com/us/strategy/big-changes-in-pokemon-tcg-sun-moon/)

Well i guess one could argue for both.

**Comment by CptSpaceToaster** [comment]
I think "Free" is a great choice... Changing this for another word is likely just going to raise errors in every application consuming the api for no good reason.

The issue isn't that it says Free.... the issue is that when you go to [the website](https://pokemontcg.io/cards/sm2-21)... it shows a Fire energy when it should be the empty shadow symbol that indicates the attack is free

**Comment by adback03** [comment]
This should be resolved. Here is the new link: https://pokemontcg.guru/card/alolan-vulpix-sun-and-moon/sm2-21
