### ISSUE TITLE
Shiny Vault Pokemon are all common

### ISSUE THREAD

**Issue by joergl87** [PokemonTCG/pokemon-tcg-data#99]
![image](https://user-images.githubusercontent.com/11797446/65603743-83c80600-dfa6-11e9-9a0f-5b60edafbb24.png)

Edit: Can see where it comes from. Still wrong.
![image](https://user-images.githubusercontent.com/11797446/65605501-795b3b80-dfa9-11e9-90ed-6e7adaa5295b.png)

**Comment by lfgcampos** [comment]
Checking pkmncards, seems like this is an easy fix.
`SV1` to `SV45` they are `Rare Holo`
`SV46` to `SV86` they are `Rare Ultra`
`SV87` to `SV94` they are `Rare Secret`

source: https://pkmncards.com/?s=set%3Ashiny-vault&display=list&sort=number&order=

**Comment by Dillonzer** [comment]
This one looks completed. @adback03 is there anything else needed on this issue?

**Comment by adback03** [comment]
This issue is solved, closing.
